### ISSUE TITLE
Not valid Win32 application Exception

### ISSUE THREAD

**Issue by ghost** [lbryio/lbry-unity#1]
After targeting WebGL:

These work...
Build Assets
Build Project

On "Package Build for LBRY"
Error:
```
Win32Exception: ApplicationName='node', CommandLine='"U:\git\lbry-unity\LBRY 3D Viewer\Assets\Editor\LBRY\package.js"', CurrentDirectory='U:\git\lbry-unity\LBRY 3D Viewer\Assets\..\LBRY', Native error= %1 is not a valid Win32 application.

System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) (at <3845a180c26b4889bc2d47593a665814>:0)
System.Diagnostics.Process.Start () (at <3845a180c26b4889bc2d47593a665814>:0)
(wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
LBRY.ExecProcess (System.String directory, System.String name, System.String args) (at Assets/Editor/LBRY/EditorSDK.cs:122)
LBRY.PackageLBRY () (at Assets/Editor/LBRY/EditorSDK.cs:97)
```

So this line fails:
`ExecProcess(Path.GetDirectoryName(targetBuildRoot), "node", packageScript);`

Prior to getting stuck here I was stuck here:
`ExecProcessShell(Path.GetDirectoryName(lbryFormatDir), "npm", "i");`

but manaully going in and calling `npm i`
so:
`U:\git\lbry-unity\LBRY 3D Viewer\Assets\Editor\LBRY\lbry-format~>npm i`
fixed the first issue which is perhaps assumed we would know that fix, but this next step i am unsure how to proceed to fix or what the expected behavior is.

NOTE:
Can you list what is the expected dev env. for this to work. I see the unity version and nodejs is installed via scoop on windows. i know node is working i did a kinda well known `node wow.js` test

I assume part of my problem is that i don't have LBRY app installed on this windows machine, i was running my lbry app on linux on same network.

**Comment by ghost** [comment]
More info:
`LBRY 3D Viewer\Assets\Editor\LBRY\package.js`

is this correct? when running:
`U:\git\lbry-unity\LBRY 3D Viewer\Assets\Editor\LBRY>node package.js`

from `cmd`:
```
Error: ENOENT: no such file or directory, scandir 'U:\git\lbry-unity\LBRY 3D Vie
wer\Assets\Editor\LBRY\Build'
```

i move the Build folder from the root of the Unity Project to the Editor Folder so:
Move this: U:\git\lbry-unity\LBRY 3D Viewer\LBRY\Build
To Here: 
```
 Directory of U:\git\lbry-unity\LBRY 3D Viewer\Assets\Editor\LBRY
<DIR> Build
```

This now doesn't give any errors:
```
U:\git\lbry-unity\LBRY 3D Viewer\Assets\Editor\LBRY>node package.js
package.js running in: U:\git\lbry-unity\LBRY 3D Viewer\Assets\Editor\LBRY
{ packDirectory: [AsyncFunction: packDirectory],
  unpackDirectory: [AsyncFunction: unpackDirectory] }
```

Keep in mind there are no asset bundles in this project. Setting a Cube up would help those at home.

**Comment by skhameneh** [comment]
Hey @communityus, thanks for filing an issue.  I'll add some more details to the readme this evening.    
  
Try checking the `Build` folder, the command should have created a `package.lbry` file.  You can publish these files direct to LBRY.  
  
Also, it sounds like you installed Node on Windows using a third-party installer.  Under normal circumstances, the modules would install automatically.  
  
I'd suggest installing the latest version of node from the official website (if not now, for future development)  
https://nodejs.org/en/download/  

You can join us on Discord if you'd like help debugging your issues:
https://chat.discord.com/

**Comment by ghost** [comment]
Thanks for the response.

It did actually build the .lbry file, I will have to do it again to find out when it worked. So the error might be false positive at least at the last step if not before.

I am happy to help. The lbry blockchain sounds like a good one. I have other questions about it on a whole. Just the simple branding that it can mean library is a real draw.

The .lbry file it generating was around 5 MB. This is where that detail would be nice. And I get this is way early alpha, just kinda stumbled on it because you guys had a flatpak. I do think I dual mined some lbc back in day with etc.

The other part, me being new to LBRY is maybe screen shots of how to upload it, on the FlatPak LBRY I see the upload cloud option. It is a bit misleading that it seems only for pictures and videos and that is most of the content, so it seems like it is a video platform. But after some digging I found it is more than that.

`[offtopic start]`
I found a southpark game? paywall sucks for discovery of course. my curiosity is peaked enough though that i will start mining again i think.

(All TMI but i wont get around to posting this anywhere helpful for you anytime soon)
`[offtopic end]`

So from what you say, I can upload this .lbry, which is a spec (using that cloud upload button) and it unpacks when downloaded as my Unity WebGL game with web assembly and multicore support I think I saw in your build button code.

Neat! Certainly say that clearly early on.

It looks like we can do more like AssetBundle delivery.

I think my main interest is Asset Bundles and a neat way to add modding to my game, through a dectralized way and everyone pays through .lbry coin. But my understanding is that I pay to upload it, and if I choose free the modders could download it for free.

Which if that is indeed the case, then I shouldn't have too many huddles on iOS because nothing would be paid from client side.

Anyways great work, I look forward to one day 1:1 integration in Unity. In general on blockchain side verbose docs great, esp. for new comers who aren't in the know.

Lastly, just a quick one off question...super glad it is bitcoin based. Any chance side chain one day instead of bitcoin fork? (maybe i don't understand, but we are not ethereum based are we?)

**Comment by skhameneh** [comment]
> I think my main interest is Asset Bundles and a neat way to add modding to my game, through a dectralized way and everyone pays through .lbry coin.

Great to hear, our long-term goal is to have wallet APIs that can be called from Unity for in-app payments / micro-transactions.

> But my understanding is that I pay to upload it, and if I choose free the modders could download it for free.

To some extent, the claim amount (LBC Deposit) can be a small fraction and abandoning a claim will recover your deposit.  The only non-refundable actions are network transaction fees, which are kept intentionally low.

> Any chance side chain one day instead of bitcoin fork?

The short answer is no, it's highly unlikely.  I'll defer details to @eukreign and @BrannonKing if they'd like to chime in.

Closing this ticket, if you have more questions, feel free to continue responding in this ticket.
